In [48]:
import pandas as pd
import numpy as np

In [49]:
df = pd.read_csv('car_prediction_data.csv')

In [50]:
df.head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [52]:
df.drop(columns=['Car_Name', 'Seller_Type', 'Transmission', 'Owner'], axis=1, inplace=True)

In [53]:
df.head(5)

   Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type
0  2014           3.35           5.59       27000    Petrol
1  2013           4.75           9.54       43000    Diesel
2  2017           7.25           9.85        6900    Petrol
3  2011           2.85           4.15        5200    Petrol
4  2014           4.60           6.87       42450    Diesel

In [54]:
df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [55]:
fuel_map = {
    "Petrol": 0,
    "Diesel": 1,
    "CNG": 2
}

df['Fuel_Type'] = df['Fuel_Type'].map(fuel_map)

In [56]:
df

     Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type
0    2014           3.35           5.59       27000          0
1    2013           4.75           9.54       43000          1
2    2017           7.25           9.85        6900          0
3    2011           2.85           4.15        5200          0
4    2014           4.60           6.87       42450          1
..    ...            ...            ...         ...        ...
296  2016           9.50          11.60       33988          1
297  2015           4.00           5.90       60000          0
298  2009           3.35          11.00       87934          0
299  2017          11.50          12.50        9000          1
300  2016           5.30           5.90        5464          0

[301 rows x 5 columns]

In [57]:
df.head(5)

   Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type
0  2014           3.35           5.59       27000          0
1  2013           4.75           9.54       43000          1
2  2017           7.25           9.85        6900          0
3  2011           2.85           4.15        5200          0
4  2014           4.60           6.87       42450          1

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           301 non-null    int64
 1   Selling_Price  301 non-null    float64
 2   Present_Price  301 non-null    float64
 3   Kms_Driven     301 non-null    int64
 4   Fuel_Type      301 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 11.9 KB

In [59]:
current_year = 2026
df['age'] = current_year-df['Year']

In [60]:
df

     Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  age
0    2014           3.35           5.59       27000          0   12
1    2013           4.75           9.54       43000          1   13
2    2017           7.25           9.85        6900          0    9
3    2011           2.85           4.15        5200          0   15
4    2014           4.60           6.87       42450          1   12
..    ...            ...            ...         ...        ...  ...
296  2016           9.50          11.60       33988          1   10
297  2015           4.00           5.90       60000          0   11
298  2009           3.35          11.00       87934          0   17
299  2017          11.50          12.50        9000          1    9
300  2016           5.30           5.90        5464          0   10

[301 rows x 6 columns]

In [64]:
df

     Selling_Price  Present_Price  Kms_Driven  Fuel_Type  age
0             3.35           5.59       27000          0   12
1             4.75           9.54       43000          1   13
2             7.25           9.85        6900          0    9
3             2.85           4.15        5200          0   15
4             4.60           6.87       42450          1   12
..             ...            ...         ...        ...  ...
296           9.50          11.60       33988          1   10
297           4.00           5.90       60000          0   11
298           3.35          11.00       87934          0   17
299          11.50          12.50        9000          1    9
300           5.30           5.90        5464          0   10

[301 rows x 5 columns]

In [18]:
df.iloc[: , 0]

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [65]:
X = df.drop('Selling_Price', axis=1)
y = df['Selling_Price'].values

In [66]:
X

     Present_Price  Kms_Driven  Fuel_Type  age
0             5.59       27000          0   12
1             9.54       43000          1   13
2             9.85        6900          0    9
3             4.15        5200          0   15
4             6.87       42450          1   12
..             ...         ...        ...  ...
296          11.60       33988          1   10
297           5.90       60000          0   11
298          11.00       87934          0   17
299          12.50        9000          1    9
300           5.90        5464          0   10

[301 rows x 4 columns]

In [67]:
y

array([ 3.35,  4.75,  7.25,  2.85,  4.6 ,  9.25,  6.75,  6.5 ,  8.75,
        7.45,  2.85,  6.85,  7.5 ,  6.1 ,  2.25,  7.75,  7.25,  7.75,
        3.25,  2.65,  2.85,  4.9 ,  4.4 ,  2.5 ,  2.9 ,  3.  ,  4.15,
        6.  ,  1.95,  7.45,  3.1 ,  2.35,  4.95,  6.  ,  5.5 ,  2.95,
        4.65,  0.35,  3.  ,  2.25,  5.85,  2.55,  1.95,  5.5 ,  1.25,
        7.5 ,  2.65,  1.05,  5.8 ,  7.75, 14.9 , 23.  , 18.  , 16.  ,
        2.75,  3.6 ,  4.5 ,  4.75,  4.1 , 19.99,  6.95,  4.5 , 18.75,
       23.5 , 33.  ,  4.75, 19.75,  9.25,  4.35, 14.25,  3.95,  4.5 ,
        7.45,  2.65,  4.9 ,  3.95,  5.5 ,  1.5 ,  5.25, 14.5 , 14.73,
        4.75, 23.  , 12.5 ,  3.49,  2.5 , 35.  ,  5.9 ,  3.45,  4.75,
        3.8 , 11.25,  3.51, 23.  ,  4.  ,  5.85, 20.75, 17.  ,  7.05,
        9.65,  1.75,  1.7 ,  1.65,  1.45,  1.35,  1.35,  1.35,  1.25,
        1.2 ,  1.2 ,  1.2 ,  1.15,  1.15,  1.15,  1.15,  1.11,  1.1 ,
        1.1 ,  1.1 ,  1.05,  1.05,  1.05,  1.05,  1.  ,  0.95,  0.9 ,
        0.9 ,  0.75,  0.8 ,  0.78,  0.75,  0.75,  0.75,  0.72,  0.65,
        0.65,  0.65,  0.65,  0.6 ,  0.6 ,  0.6 ,  0.6 ,  0.6 ,  0.6 ,
        0.6 ,  0.6 ,  0.55,  0.55,  0.52,  0.51,  0.5 ,  0.5 ,  0.5 ,
        0.5 ,  0.5 ,  0.48,  0.48,  0.48,  0.48,  0.45,  0.45,  0.45,
        0.45,  0.45,  0.45,  0.45,  0.45,  0.42,  0.42,  0.4 ,  0.4 ,
        0.4 ,  0.4 ,  0.4 ,  0.38,  0.38,  0.35,  0.35,  0.35,  0.31,
        0.3 ,  0.3 ,  0.3 ,  0.27,  0.25,  0.25,  0.25,  0.25,  0.25,
        0.2 ,  0.2 ,  0.2 ,  0.2 ,  0.2 ,  0.2 ,  0.18,  0.17,  0.16,
        0.15,  0.12,  0.1 ,  3.25,  4.4 ,  2.95,  2.75,  5.25,  5.75,
        5.15,  7.9 ,  4.85,  3.1 , 11.75, 11.25,  2.9 ,  5.25,  4.5 ,
        2.9 ,  3.15,  6.45,  4.5 ,  3.5 ,  4.5 ,  6.  ,  8.25,  5.11,
        2.7 ,  5.25,  2.55,  4.95,  3.1 ,  6.15,  9.25, 11.45,  3.9 ,
        5.5 ,  9.1 ,  3.1 , 11.25,  4.8 ,  2.  ,  5.35,  4.75,  4.4 ,
        6.25,  5.95,  5.2 ,  3.75,  5.95,  4.  ,  5.25, 12.9 ,  5.  ,
        5.4 ,  7.2 ,  5.25,  3.  , 10.25,  8.5 ,  8.4 ,  3.9 ,  9.15,
        5.5 ,  4.  ,  6.6 ,  4.  ,  6.5 ,  3.65,  8.35,  4.8 ,  6.7 ,
        4.1 ,  3.  ,  7.5 ,  2.25,  5.3 , 10.9 ,  8.65,  9.7 ,  6.  ,
        6.25,  5.25,  2.1 ,  8.25,  8.99,  3.5 ,  7.4 ,  5.65,  5.75,
        8.4 , 10.11,  4.5 ,  5.4 ,  6.4 ,  3.25,  3.75,  8.55,  9.5 ,
        4.  ,  3.35, 11.5 ,  5.3 ])

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [69]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [70]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression()

In [71]:
predict = regression.predict(X_test)

In [72]:
from sklearn.metrics import r2_score
score = r2_score(y_test, predict)
score

0.8743898758239812

In [74]:
input = scaler.transform([[5.51, 27000, 0, 15]])

predict1 = regression.predict(input)
predict1

C:\Users\kavis\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([2.22110044])

In [75]:
import pickle
pickle.dump(regression, open('regression.pkl', 'wb'))

In [76]:
pickle.dump(scaler, open('scaler.pkl', 'wb'))

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Selling_Price     301 non-null    float64
 1   Present_Price     301 non-null    float64
 2   Kms_Driven        301 non-null    int64
 3   Fuel_Type_Diesel  301 non-null    float64
 4   Fuel_Type_Petrol  301 non-null    float64
 5   age               301 non-null    int64
dtypes: float64(4), int64(2)
memory usage: 14.2 KB